name: Node.js CI

on: [push]

jobs:
  build:
    # runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      # The apt-gets prevent cwebp compiling from source each time.
      - run: sudo apt-get update
      - run: sudo apt-get install libglu1 libxi6 -y
      - name: Install project dependencies
        run: npm ci
      - name: Build package and publish
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm version prerelease --preid=beta
          npm publish --ignore-scripts
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
