name: Node.js CI

on: [push]

jobs:
  build:
    # runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      # The apt-gets prevent cwebp compiling from source each time.
      - run: apt-get update
      - run: apt-get install libglu1 -y
      - run: npm ci
      - run: npm run roll:lib
      # - run: npm test
